# authorName: default
# experimentName: example_mnist_pytorch
# trialConcurrency: 1
# maxExecDuration: 10000h
# maxTrialNum: 10
# #choice: local, remote, pai
# trainingServicePlatform: local
# searchSpacePath: search_space.json
# #choice: true, false
# useAnnotation: false
# # useActiveGpu: true
# # maxTrialNumPerGpu: 0
# tuner:
#   #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
#   #SMAC (SMAC should be installed through nnictl)
#   builtinTunerName: TPE
#   classArgs:
#     #choice: maximize, minimize
#     optimize_mode: maximize
# trial:
#   command: python sac_v2_my_TCN_critic_bn_V2_save_V3.py
#   codeDir: .
#   gpuNum: 0
#   # useActiveGpu: true

# authorName: default
# experimentName: sac_vibration
# trialConcurrency: 1
# maxExecDuration: 1000h  #1h  {s,m,h,d}
# maxTrialNum: 1000
# #choice: local, remote, pai
# trainingServicePlatform: local
# searchSpacePath: search_space.json
# #choice: true, false
# useAnnotation: false
# tuner:
#   #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
#   #SMAC (SMAC should be installed through nnictl)
#   builtinTunerName: TPE
#   classArgs:
#     #choice: maximize, minimize
#     optimize_mode: maximize
#   # gpuIndices: '1'  
# trial:
#   command: CUDA_VISIBLE_DEVICES=0 python sac_v2_my_TCN_critic_bn_V2_save_V4.py
#   codeDir: .
#   gpuNum: 1



authorName: default
experimentName: sac_vibration
trialConcurrency: 1
maxExecDuration: 10000h
maxTrialNum: 10000
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python3 sac_v2_my_TCN_critic_bn_V2_save_V5.py
  codeDir: .
  gpuNum: 1

localConfig:
  useActiveGpu: true